### ISSUE TITLE
Notch Filter order read as a non-numeric value

### ISSUE THREAD

**Issue by Rommelchr** [widmann/firfilt#10]
Hello, 

I'm on my first eeglab project, and I'm having an eeggiltnew() error at line 175 while using the GUI. This happens after trying to apply an 8th order notch filter on a .study file that contains 10 datasets. 

pop_eegfiltnew error: argument 'filtorder' must be numeric, 
This is not a bug (Error occured in function pop_eegfiltnew() at line 175)

I typed 58 for lowpass, 62 for highpass, 8 for filter order, and enabled the notch option.

I'm comparing this filter against others so I need to report the filter order. If I cannot use an 8th order filter, I'd like to know if there's a way to get the default order.

Any answers appreciated. Thank you.

**Comment by widmann** [comment]
I can replicate the issue. This is due to filtorder option not properly converted to numeric. The bug was presumably introduced by a commit by @arnodelorme (deb7b081308a1a1ef94184087bceab38ce68ba8c) in 2018. Arno, do you remember the reason or any details for this implementation (line 127 in most recent version)?

I will try to fix and issue a new version. Somehow appears urgent but on the other hand apparently nobody tried to use custom (non-default) filter order since 2018?! Somewhat perplexing given that the default order is based on a relatively unsophisticated heuristic.

Anyway, you won't succeed with filter order 8 either. This is (far) too low (somewhere in the range of several hundreds with typical sampling rates). You must not directly compare FIR and IIR filter orders. Please check the paper (https://home.uni-leipzig.de/~biocog/eprints/widmann_a2015jneuroscimeth250_34.pdf) for a detailed description how to derive filter order.

@arnodelorme, I noticed that the EEGLAB GUI reporting errors limits the number of characters. When trying to replicate the reported problem (with order 8) with a fixed version of pop_eegfiltnew (resulting in an error due to order < min order) the recommended optimal filter order is cut off. Could you please try to replicate (and fix in case replicable for example by breaking long lines)?

Best,
Andreas

**Comment by widmann** [comment]
Fixed in 22aba6ba51cc6e142d08a82c68f99261cb52baaa.

@arnodelorme, could you please update the firfilt plugin reference to cc1df0e? Thanks!

**Comment by arnodelorme** [comment]
The error shows up for me. Probably a platform difference.

**Comment by arnodelorme** [comment]
![Screen Shot 2022-08-15 at 10 17 01 AM](https://user-images.githubusercontent.com/1872705/184683665-31b32ecd-a5b0-436e-b342-64f3993ef19e.png)

**Comment by arnodelorme** [comment]
We should put the message on two rows (add character 10 before "For better...")

**Comment by widmann** [comment]
> We should put the message on two rows (add character 10 before "For better...")

Fixed in 5f13998.

Thanks for reporting the problem!
Andreas
